# PP-LiteSeg semantic segmentation (Cityscapes, 19 classes).
model_path: ~/.cache/models/vision/pp_liteseg/pp_liteseg.q.onnx
test_image: ~/.cache/assets/image/009_test_unet.jpg
class: deploy.pp_liteseg.PPLiteSeg
default_params:
  num_threads: 8
  num_classes: 19
  providers:
    - SpaceMITExecutionProvider
